### ISSUE TITLE
System.NullReferenceException using Range Property

### ISSUE THREAD

**Issue by RobertoCalderonM** [NetOfficeFw/NetOffice#304] opened 2020-11-14 04:11 UTC
Trying to copy-paste duplicates of Excel page in the same worksheet N times depending on parameters. When calling certain Properties like Cells, Range, or Activate() Method, Program fails throwing a Null Reference Exception.  

```
public void AdecuarAreaDeImpresión(string rutaExcelAEditar, string hoja, string llaveReferencia, int cantidadDeObjectos)
        {
            using (var excelApplication = new WrapperAplicaciónExcel())
            {
                var workbookTemplate = excelApplication.AplicaciónExcel.Workbooks.Open(rutaExcelAEditar);
                Worksheet sheet = workbookTemplate.DevolverHoja(hoja); 
                if (sheet==null) throw new Exception("Hoja no encontrada"); //checking nullity of sheet.
                if (cantidadDeObjectos <= 0) return;

                _**Range range = sheet.Range(sheet.Cells[1, 1], sheet.Cells[48, 8]);** //This line fails._
                int objectosPorHoja=range.Find(llaveReferencia).Count;
                int cantidadDeCopias = (int) Math.Floor((decimal) cantidadDeObjectos / (decimal) objectosPorHoja);
                range.Copy();
                int rangeRows= range.Rows.Count;
                for (var i = 1; i <= cantidadDeCopias; i++)
                {
                    int row = (i * rangeRows) + 1;
                    var pasteRange = (Range)sheet.Cells[row, 0];
                    pasteRange.PasteSpecial();
                }
                workbookTemplate.Save();
            }
        }
```

This code returning variable 'sheet' correctly

   ```
 public static Worksheet DevolverHoja(this Workbook workbook, string sheetName)
        {
            if (workbook.Sheets == null || workbook.Sheets.Count == 0)
                return null;
            foreach (Worksheet sheet in workbook.Sheets)
            {
                if (sheet.Name.Equals(sheetName))
                {
                    return sheet;
                }
            }
            return null;
        }
```

This method also is working as expected

```
public void RemplazarValores(string rutaExcelAEditar, List<(string llave, string valor)> mapaDeValores)
        {
            using (var excelApplication = new WrapperAplicaciónExcel())
            {
                var workbookTemplate = excelApplication.AplicaciónExcel.Workbooks.Open(rutaExcelAEditar);
                foreach (Worksheet workbootSheet in workbookTemplate.Worksheets)
                {
                    mapaDeValores.ForEach(t => workbootSheet.Cells.Replace(t.llave, t.valor));
                }
                workbookTemplate.Save();
            }
        }
```

**Comment by jozefizso** [comment] 2020-11-14 09:31
Please, provide the exception message and stacktrace.

**Comment by RobertoCalderonM** [comment] 2020-11-14 16:36
This is all could gather from the console for this process.

```
'ForeverMoments.exe' (CLR v4.0.30319: ForeverMoments.exe): Loaded 'C:\windows\assembly\GAC_MSIL\Microsoft.Office.Interop.Excel\15.0.0.0__71e9bce111e9429c\Microsoft.Office.Interop.Excel.dll'. Module was built without symbols.
'ForeverMoments.exe' (CLR v4.0.30319: ForeverMoments.exe): Loaded 'C:\windows\assembly\GAC_MSIL\office\15.0.0.0__71e9bce111e9429c\office.dll'. Module was built without symbols.
'ForeverMoments.exe' (CLR v4.0.30319: ForeverMoments.exe): Loaded 'D:\Visual Studio\Visual Studio Projects\Proyecto_ForeverMoments\Presentación\ForeverMoments\bin\Release\OfficeApi.dll'. 
'ForeverMoments.exe' (CLR v4.0.30319: ForeverMoments.exe): Loaded 'D:\Visual Studio\Visual Studio Projects\Proyecto_ForeverMoments\Presentación\ForeverMoments\bin\Release\VBIDEApi.dll'. 
'ForeverMoments.exe' (CLR v4.0.30319: ForeverMoments.exe): Loaded 'C:\windows\Microsoft.Net\assembly\GAC_32\CustomMarshalers\v4.0_4.0.0.0__b03f5f7f11d50a3a\CustomMarshalers.dll'. 
Exception thrown: 'System.NullReferenceException' in ForeverMoments.exe
Object reference not set to an instance of an object.

The thread 0x12c8 has exited with code 0 (0x0).
Exception thrown: 'System.NullReferenceException' in ForeverMoments.exe
Object reference not set to an instance of an object.

Exception thrown: 'System.Reflection.TargetInvocationException' in mscorlib.dll
2020-11-14 10:34:03,008 [1] ERROR ForeverMoments.Program Bob - System.NullReferenceException: Object reference not set to an instance of an object.
   at ForeverMoments.Capa_Presentación.Cotizadores.ResumenCotización.backgroundWorker1_RunWorkerCompleted(Object sender, RunWorkerCompletedEventArgs e) in D:\Visual Studio\Visual Studio Projects\Proyecto_ForeverMoments\Presentación\ForeverMoments\Capa_Presentación\Cotizadores\ResumenCotización.cs:line 166
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.AsyncOperationCompleted(Object arg)
```

**Comment by jozefizso** [comment] 2020-11-14 20:46
Based on the stacktrace I cannot tell what the problem is.

You should use debugger to see which variable is null or change your code to be able to troubleshoot the bug.

**Comment by RobertoCalderonM** [comment] 2020-11-14 23:11
Found the issue. It seemed that the debugger (not sure of the reason) was focusing on an incorrect line. The null pointer exception was thrown by this line:
`int objectosPorHoja=range.Find(llaveReferencia).Count; (No values found, so the returned range is null).`
Solved it using 
```
int? objectosPorHoja = range.Find(what: llaveReferencia, Missing.Value,lookIn: XlFindLookIn.xlValues,
                    Missing.Value, Missing.Value,searchDirection: XlSearchDirection.xlNext,matchCase: false,matchByte: false, Missing.Value)?.Count;
```

**Comment by jozefizso** [comment] 2020-11-16 11:57
Stacktrace reports the exception was thrown at `backgroundWorker1_RunWorkerCompleted(Object sender, RunWorkerCompletedEventArgs e) in ResumenCotización.cs:line 166`.

Do I understand it correctly that `NullReferenceException` is thrown in `ResumenCotización.cs` on line 166, which is `Range range = sheet.Range(sheet.Cells[1, 1], sheet.Cells[48, 8]);` but it actually fails on line `int objectosPorHoja=range.Find(llaveReferencia).Count;` which should be 167?
`

**Comment by jozefizso** [comment] 2022-08-16 18:30
Closing as no information was provided.

**Closed by jozefizso** 2022-08-16 18:30 UTC
Labels: support, moreinfo
