### ISSUE TITLE
How can i write a rtd_server function by netoffice?

### ISSUE THREAD

**Issue by 571821151** [NetOfficeFw/NetOffice#225] opened 2018-10-23 06:06 UTC
i can not write this by netoffice ,who can give me a demo

**Comment by 571821151** [comment] 2018-10-24 01:08
the RefreshData function can not be executed  by  xlRTDUpdate.UpdateNotify();

**Comment by jozefizso** [comment] 2018-10-24 16:54
Closing as duplicate of #222

**Closed by jozefizso** 2018-10-24 16:54 UTC
Labels: duplicate, support
