### ISSUE TITLE
Set NetOffice Assemblypath

### ISSUE THREAD

**Issue by ClearMemory** [NetOfficeFw/NetOffice#245] opened 2019-05-22 09:43 UTC
I try to open a doc document in my service.
I succeed in debug mode.
In the release mode, the service terminates without exception when importing the document.
I suspect that the assembly path is wrong here because the process is executed in C:\windows\ ... and not in the release directory.
Is it possible to set the execution path of the NetOffice components?

**Comment by jozefizso** [comment] 2019-10-31 13:31
This issue is specific to your deployment scenario.

Closing as this is out of the scope of the library and from the description of the issue is not enough to provide a guidance.

**Closed by jozefizso** 2019-10-31 13:31 UTC
Labels: external, support
