### ISSUE TITLE
Excel.exe not closing after quit and dispose

### ISSUE THREAD

**Issue by zhofre** [NetOfficeFw/NetOffice#220] opened 2018-10-04 14:18 UTC
we are using the NetOffice Nuget (1.7.4.4) to read some excels into our application and notice that Excel.exe doesn't close properly.

When we just open the application and immediatelty quit, then we see the process appearing and being shut down properly.

            using (var app = new Excel.Application())
            {
                app.Quit();
            }

But as soon as we create a new workbook, or we open een existing file, then the process stays open in the list of background processes.

            using (var app = new Excel.Application())
            {
                using (var wb = app.Workbooks.Add())
                {
                    wb.Close(false);
                }
                app.Quit();
            }

Running [Example01.cs](https://github.com/NetOfficeFw/Samples/blob/master/Excel/01%20Excel%20Automation%20Sample/ExcelExamples/Examples/Example01.cs) in a console also leaves the Excel.exe process running in the background.

Does anyone know how to fix this (other than killing the processes with brute force)?

Note: running Excel2016 (16.0.7766.2099) on Windows 10 Enterprise.

**Comment by matteshe** [comment] 2018-10-05 18:41
It's good not using using. The Function Workbooks hold the instance. You need to close this as well in order to close it properly. At least this is what i do. I implement my own dispose function to shutdown all in an ordered way.

Am 4. Oktober 2018 16:18:19 MESZ schrieb Geoffrey Decan <notifications@github.com>:

**Comment by Charltsing** [comment] 2018-10-17 14:07
> we are using the NetOffice Nuget (1.7.4.4) to read some excels into our application and notice that Excel.exe doesn't close properly.
> 
> When we just open the application and immediatelty quit, then we see the process appearing and being shut down properly.
> 
> ```
>         using (var app = new Excel.Application())
>         {
>             app.Quit();
>         }
> ```
> But as soon as we create a new workbook, or we open een existing file, then the process stays open in the list of background processes.
> 
> ```
>         using (var app = new Excel.Application())
>         {
>             using (var wb = app.Workbooks.Add())
>             {
>                 wb.Close(false);
>             }
>             app.Quit();
>         }
> ```
> Running [Example01.cs](https://github.com/NetOfficeFw/Samples/blob/master/Excel/01%20Excel%20Automation%20Sample/ExcelExamples/Examples/Example01.cs) in a console also leaves the Excel.exe process running in the background.
> 
> Does anyone know how to fix this (other than killing the processes with brute force)?
> 
> Note: running Excel2016 (16.0.7766.2099) on Windows 10 Enterprise.

using (var app = new Excel.Application())
        {
using (var ws = app.Workbooks)
            using (var wb = ws.Add())
            {
                wb.Close(false);
            }
}
            app.Quit();
        }

**Comment by jozefizso** [comment] 2018-10-17 15:00
You can check how many proxy objects do you have running before and after calling an Excel API :

```
var count = NetOffice.Core.Default.ProxyCount;
```

You can use this value to see if you are disposing COM proxies correctly. Common mistake is to use iterators and not store them in a variable which will be disposed - this leaks COM object reference and will cause the MS Office app to not shutdown.


Other way to determine the problem is to use Full Memory Dump from Process Explorer.
You can examine the dump (actually, several memory dumps) with tools like DebugDiag to see which code is leaking references.

**Comment by jozefizso** [comment] 2018-11-01 19:28
Please provide more info about the issue.

**Closed by jozefizso** 2018-11-01 19:28 UTC
Labels: moreinfo, ms-excel
