### ISSUE TITLE
Office 365/2016 Question: Outlook Instance / CreateMail only works when Outlook is closed. How to open "existing" Instance?

### ISSUE THREAD

**Issue by DanielKarr87** [NetOfficeFw/NetOffice#7] opened 2016-12-07 13:36 UTC
My Code looks like this:

    public NetOffice.OutlookApi.Application GetOutlookApplicationInstance()
    {
            NetOffice.OutlookApi.Application response = null;
            ClearError();
            try
            {
                try
                {
                    response = new NetOffice.OutlookApi.Application();
                }
                catch (System.Exception ex) { SetError(ex); }
            }
            catch (System.Exception ex) { SetError(ex); }
            
            return response;
    }

    this.Outlook_Instance = GetOutlookApplicationInstance();
    if (this.Outlook_Instance != null)
    {
    try { MailDokument =    (NetOffice.OutlookApi.MailItem)Outlook_Instance.CreateItem(NetOffice.OutlookApi.Enums.OlItemType.olMailItem); } catch (System.Exception ex) { }
    ...
    }

It seems that, when Outlook 2016 (in this Case it was Outlook 2016 out of Office 365 Version) is opened, it didn't get the ApplicationInstance or can't create a MailItem. When Outlook is closed, it works.
I didn't see the Problem. Did i miss something?

**Comment by ErwanJezequel** [comment] 2017-04-28 13:59
I have the same problem... 
Did you find a workaround ?

It can only open an existing instance if Outlook was launched as admin.

**Comment by DanielKarr87** [comment] 2017-04-28 16:16
Sort of, i'm trying all available methods with try catch around it. It seems that you can hook to the existing instance by searching. Must Check when i'm in the office tuesday.
Von Outlook gesendet.
________________________________
Von: ErwanJezequel <notifications@github.com>
Gesendet: Freitag, 28. April 2017 15:59:40
An: NetOfficeFw/NetOffice
Cc: DanielKarr87; Author
Betreff: Re: [NetOfficeFw/NetOffice] Office 365/2016 Question: Outlook Instance / CreateMail only works when Outlook is closed. How to open "existing" Instance? (#7)


I have the same problem...
Did you find a workaround ?

It can only open an existing instance if Outlook was launched as admin.

**Comment by ErwanJezequel** [comment] 2017-04-28 16:19
It only happens when I run my application with Visual Studio. When I use my production application, it works fine. 
So... I quit trying to find a workaround...

**Comment by DanielKarr87** [comment] 2017-04-28 22:51
This happened to me once, when opening outlook with admin rights it doesnt appear. Why this happened ... dont ask

Von Outlook gesendet.
________________________________
Von: ErwanJezequel <notifications@github.com>
Gesendet: Freitag, 28. April 2017 18:19:38
An: NetOfficeFw/NetOffice
Cc: DanielKarr87; Author
Betreff: Re: [NetOfficeFw/NetOffice] Office 365/2016 Question: Outlook Instance / CreateMail only works when Outlook is closed. How to open "existing" Instance? (#7)


It only happens when I run my application with Visual Studio. When I use my production application, it works fine.
So... I quit trying to find a workaround...

**Comment by jozefizso** [comment] 2017-06-23 15:30
As described in the SO answer, this may be caused by Visual Studio running with different security tokens then other Outlook processes and thus fails to create new COM automation instance.

Closing, as this behavior depends on end-user or developer setup.

**Closed by jozefizso** 2017-06-23 15:30 UTC
Labels: question
